### PR TITLE
fix(security): complete Codex Security M8

### LINKED ISSUE #863: [Codex Security M8] CMS, moderation, and filter integrity
**Source**: Codex security findings roadmap, M8
**Milestone**: Codex Security M8 — CMS moderation filter integrity

## Goal
Close tenant isolation and ownership gaps in CMS/moderation/filter write paths.

## Sub-issue structure
This parent is intentionally tracked with GitHub sub-issues. Do not replace the nested sub-issues with checkbox-only task lists.

## Planned sub-issues
- #40: `fix(cms): tenant-scope slug lookups` — CMS slug lookups are tenant-scoped with dual-read/backfill compatibility and no cross-tenant exposure.
- #41: `fix(cms): enforce category series and draft permissions` — CMS category, series, article, and draft mutations enforce admin/owner permissions consistently.
- #54: `fix(moderation): avoid recursive review writes` — Moderation stream processing does not rewrite reviews in a way that recursively emits unbounded MODIFY events.
- #55: `fix(filters): authorize keyword mutations` — Filter keyword update/delete verifies keyword ownership by filter and user before mutation.

## Specialist walks referenced
- Federation trust: as applicable per child issue
- Contract: backward-compatible semantic refinements via preserve-mastodon-api-compat
- Schema: completed via validate-schema for schema-adjacent children

## Parent acceptance
All child issues are closed, full local hard gate has passed for the milestone PR(s), and rollout notes are ready for dev → staging → live.

## Validation
- `go test ./...`
- `go vet ./...`
- `gofmt -l .`
- `go build -o lesser ./cmd/lesser`
- `./lesser build lambdas`
- `./lesser verify ci`

## Stage rollout checkpoints
- Merged to main
- Deployed to dev
- Dev soak complete
- Deployed to staging (if used)
- Staging soak complete
- Deployed to live
- Post-deploy monitoring verified

### PR DESCRIPTION
**Pull request by aron23**
## Milestone
[Codex Security M8] CMS, moderation, and filter integrity — close tenant isolation and ownership gaps in CMS/moderation/filter write paths.

Closes #863.

## Classification
security / schema / contract-stability / operational-reliability

## Surfaces affected
- CMS slug index helpers and CMS slug lookup paths for articles, categories, publications, and series
- GraphQL CMS mutations for categories, articles, and series assignments
- Moderation stream processor review handling and consensus evaluation
- Mastodon-compatible filter keyword update/delete handlers under `/api/v2/filters/*`

## Specialist walks referenced
- Federation trust: no ActivityPub signing, verification, actor identity, inbox/outbox, relay, or delivery changes.
- Contract / API: semantic hardening only. GraphQL schema and OpenAPI files remain up to date; filter keyword ownership failures now return not-found instead of mutating cross-filter IDs.
- Schema: additive tenant-scoped CMS slug PK helpers and optional `Series.Tenant`; no TableTheory tag, GSI, or existing PK/SK rewrites. Reads dual-read legacy global indexes, verify tenant ownership before returning, and backfill tenant-scoped indexes.
- Framework: idiomatic AppTheory/TableTheory usage; no framework patches.

## Consumer impact
- Operators keep legacy CMS content readable while new/backfilled slug indexes are tenant-scoped.
- CMS admins now own shared taxonomy mutations; article authors/admins must own referenced series before attaching articles.
- Moderation stream processing avoids recursive review writes from DynamoDB Streams side effects.
- Filter clients see safer 404 behavior for keyword IDs outside the owned filter, with unchanged response schema.

## Tasks
- [x] Tenant-scope CMS slug lookups with dual-read/backfill and no cross-tenant exposure.
- [x] Enforce CMS category/series/article/draft mutation permissions consistently.
- [x] Avoid recursive moderation review writes from stream processing.
- [x] Verify filter keyword ownership before update/delete mutation.

## Validation
- `gofmt -l .` (empty)
- Targeted: `go test ./cmd/moderation-processor ./cmd/api/handlers ./pkg/services/cms ./pkg/moderation ./pkg/storage/models ./graph`
- `go test ./...`
- `go vet ./...`
- `go build -o lesser ./cmd/lesser`
- `./lesser build lambdas`
- `./lesser verify ci`
  - overall coverage: 87.568%
  - pkg coverage: 90.024%
  - cmd coverage: 90.016%

## Stage rollout plan (handoff to deploy-instance)
- [ ] Merged to main
- [ ] Deployed to dev
- [ ] Dev soak complete
- [ ] Deployed to staging (if used)
- [ ] Staging soak complete
- [ ] Deployed to live

## Cross-repo coordination
None required. No sibling-repo contract or release-artifact shape changes.

## Notes
Legacy series rows with an empty `tenant` remain accepted during dual-read/backfill for compatibility; newly created series rows are tenant-tagged.

### CODE REVIEW

File: graph/mutation_resolvers_cms.go [hunk 1]
```diff
@@ -840,12 +854,35 @@ func (r *mutationResolver) ReorderSeriesArticles(ctx context.Context, seriesID s
...
+	}
+	if !r.isAdmin(ctx, username) && !strings.EqualFold(authorID, username) {
+		return errors.New("insufficient privileges for series update")
+	}
+
+	seriesSvc := r.Registry.Series()
+	if seriesSvc == nil {
+		return errors.New("series service is not available")
+	}
+	if _, err := seriesSvc.GetSeries(ctx, authorID, rawID); err != nil {
```
Comment (aron23) [inline graph/mutation_resolvers_cms.go]: This verifies that a series with this author/id exists, but it does not verify that the loaded series belongs to the current tenant. `CreateSeries` now stamps `Series.Tenant`, and slug lookup checks it, but this helper still lets `alice` on tenant B attach tenant A's `alice|seriesID` to a tenant B article. I reproduced that with a temporary test by creating the series under `https://tenant-a.example`, switching the resolver BaseURL to `https://tenant-b.example`, and calling `CreateArticle(... SeriesID: tenantASeries.ID)` as `alice`; it succeeded. Please load the series here and require `series.Tenant` to match `r.getDomain()` (with an explicit legacy-empty policy).

**Review by aron23 — COMMENTED** [review]
Tier 1 review at head `14f3a137`.

Local validation passed:
- `gofmt -l .` (empty)
- targeted: `go test ./cmd/moderation-processor ./cmd/api/handlers ./pkg/services/cms ./pkg/moderation ./pkg/storage/models ./graph`
- `go test ./...`
- `go vet ./...`
- `go build -o lesser ./cmd/lesser`
- `./lesser build lambdas` (38 artifacts)
- `./lesser verify ci` (overall 87.569%, pkg 90.025%, cmd 90.019%)

GitHub checks: CodeQL / Analyze / Snyk are green; GitHub `verify` was still pending when I checked.

Merge-blocking finding: the PR adds `Series.Tenant` and tenant-scoped series slug lookup, but the direct series mutation/attachment paths still authorize only on `authorID == username` before/after `GetSeries`. In a shared store, the same username from another tenant can mutate or attach another tenant’s series by GraphQL ID. I verified with temporary repro tests: create a series as `alice` with `BaseURL=https://tenant-a.example`, switch the resolver to `https://tenant-b.example`, then `UpdateSeries` as `alice` succeeds; `CreateArticle` in tenant-b with the tenant-a `series.ID` also succeeds.

The low-cost fix is to centralize series loading/authorization so `UpdateSeries`, `DeleteSeries`, `AddArticleToSeries`, `RemoveArticleFromSeries`, `ReorderSeriesArticles`, and `ensureCanUseCMSSeries` all verify the loaded `series.Tenant` against `r.getDomain()` (with an explicit policy for legacy empty-tenant rows). Also use the loaded series tenant, not the current request tenant, when deleting the tenant-scoped series slug index.

Non-blocking reliability note: `handleNewReview` now parses the stream review but `ProcessPersistedReview` re-queries reviews without using that triggering row. `GetModerationReviews` does not request a strong/consistent read, so if the just-inserted review is not visible on that query, consensus can be skipped with no retry now that review MODIFY events are ignored. Consider either merging the stream review into the fetched set without rewriting it, or making the persisted-review read explicitly consistent if TableTheory/DynamoDB supports it.

File: graph/mutation_resolvers_cms.go [hunk 2]
```diff
@@ -348,6 +356,9 @@ func (r *mutationResolver) UpdateArticle(ctx context.Context, id string, input m
 	if err := r.ensureAuthorCanWriteCMS(ctx, username, article.AttributedTo); err != nil {
```
Comment (aron23) [inline graph/mutation_resolvers_cms.go:356]: The series-specific tenant check is fixed, but this article write gate still falls back to `ensureAuthorCanWriteCMS`, whose existing normalized-username fallback accepts `https://tenant-a.example/users/alice` when the current resolver domain is `tenant-b.example` and the authenticated username is `alice`. I verified with a temporary repro: create an article under `BaseURL=https://tenant-a.example`, switch to `https://tenant-b.example`, then `UpdateArticle` as `alice` on the tenant-a article ID succeeds. This leaves a same-username cross-tenant mutation path for article updates/deletes/restores and for category/series membership changes via article update. Please make this ownership check tenant-aware before treating M8 article write permissions as closed.

**Review by aron23 — COMMENTED** [review]
Tier 1 re-review at updated head `284e31a`.

What changed since my prior review:
- The previous series-specific blocker is addressed. `loadAuthorizedCMSSeries` now centralizes the author + tenant check for `UpdateSeries`, `DeleteSeries`, `AddArticleToSeries`, `RemoveArticleFromSeries`, `ReorderSeriesArticles`, and `ensureCanUseCMSSeries`.
- The delete path now uses the loaded series tenant for slug-index deletion.
- Regression coverage was added in `TestRound12CMS_SeriesMutationRejectsCrossTenantSeries`.

Local validation passed at this head:
- `gofmt -l .` (empty)
- targeted: `go test ./graph -run 'TestRound12CMS_SeriesMutationRejectsCrossTenantSeries|TestRound12CMS_MutationPermissions' -count=1`
- targeted changed packages: `go test ./cmd/moderation-processor ./cmd/api/handlers ./pkg/services/cms ./pkg/moderation ./pkg/storage/models ./graph`
- `go test ./...`
- `go vet ./...`
- `go build -o lesser ./cmd/lesser`
- `./lesser build lambdas` (38 artifacts)
- `./lesser verify ci` (overall 87.584%, pkg 90.025%, cmd 90.019%)

GitHub checks: Analyze / CodeQL / Snyk are green; GitHub `verify` was still pending when I checked.

Remaining merge-blocking finding: the same tenant-isolation class remains on direct article write paths. `UpdateArticle`, `DeleteArticle`, and `RestoreRevision` authorize through `ensureAuthorCanWriteCMS`, and that helper still permits a match on normalized username even when the stored actor domain is a different tenant. Temporary repro: create an article as `alice` with `BaseURL=https://tenant-a.example`, switch the resolver to `https://tenant-b.example`, then call `UpdateArticle` as `alice` on the tenant-a article ID; the update succeeds.

Cost of leaving this: M8 would close series attachment but still permit same-username cross-tenant article mutation by direct object ID, and that also gives a path to category/series membership changes through article updates. Low-cost fix direction: make CMS article write ownership tenant-aware — either require `article.AttributedTo == cmsLocalActorID(r.getDomain(), username)` for new tenant-scoped content, or first require the article/object ID host/current tenant to match before allowing the legacy normalized-username fallback. This will likely require adjusting the existing `TestEnsureAuthorCanWriteCMSAllowsNormalizedUsernameMatch` expectation or scoping it to a deliberate legacy compatibility path.

**Review by aron23 — COMMENTED** [review]
Tier 1 re-review at head `e205d0b`.

Observed in the update:
- The previous article write-path blocker is addressed. `ensureAuthorCanWriteCMS` now checks the host from URL-shaped `attributedTo` values before falling back to normalized username matching, so `https://tenant-a.example/users/alice` is rejected when the active resolver domain is `tenant-b.example`.
- The legacy plain-username path is still explicit and covered by `TestEnsureAuthorCanWriteCMSAllowsLegacyUsernameMatch`.
- `TestRound12CMS_ArticleWritesRejectCrossTenantArticle` now covers the prior repro class across `UpdateArticle`, `RestoreRevision`, and `DeleteArticle`; those paths reject the tenant-switched article.

Local validation passed:
- `gofmt -l .` (empty)
- targeted: `go test ./graph -run 'TestEnsureAuthorCanWriteCMS|TestRound12CMS_(SeriesMutationRejectsCrossTenantSeries|ArticleWritesRejectCrossTenantArticle|MutationPermissions)' -count=1`
- targeted changed packages: `go test ./cmd/moderation-processor ./cmd/api/handlers ./pkg/services/cms ./pkg/moderation ./pkg/storage/models ./graph`
- `go test ./...`
- `go vet ./...`
- `go build -o lesser ./cmd/lesser`
- `./lesser build lambdas` (38 artifacts)
- `./lesser verify ci` (overall 87.586%, pkg 90.025%, cmd 90.019%)

GitHub checks when I checked: Analyze / CodeQL / Snyk are green; GitHub `verify` is still pending.

I do not see a remaining merge-blocking Arch finding from this pass. The earlier moderation stream consistency note remains non-blocking.

File: graph/mutation_resolvers_cms.go (hunk 2 above)
Comment (aron23) [reply graph/mutation_resolvers_cms.go:356]: Verified at `e205d0b`: this blocker is resolved. `ensureAuthorCanWriteCMS` now rejects URL-shaped `attributedTo` values whose host differs from `r.getDomain()` before the normalized username fallback, and `TestRound12CMS_ArticleWritesRejectCrossTenantArticle` covers `UpdateArticle`, `RestoreRevision`, and `DeleteArticle` under the tenant-switch repro. No remaining merge-blocking finding from this thread.
