### PR TITLE
fix(security): complete Codex Security M9

### LINKED ISSUE #868: [Codex Security M9] Browser, CLI, release, and secret hardening
**Source**: Codex security findings roadmap, M9
**Milestone**: Codex Security M9 — Browser CLI release secret hardening

## Goal
Harden browser headers, SSR host reflection, release packaging, local secrets, init-admin, and privacy hashes.

## Sub-issue structure
This parent is intentionally tracked with GitHub sub-issues. Do not replace the nested sub-issues with checkbox-only task lists.

## Planned sub-issues
- #45: `fix(api): restore restrictive browser security headers` — CORS/security headers are restrictive by default while preserving documented operator configuration points.
- #46: `fix(frontend): protect ssr link responses` — SSR /l placeholder responses escape Host-derived values and receive CSP/security headers.
- #47: `fix(release): harden asset packaging` — Release packaging refuses unsafe symlinks and release assembly handles hyphenated slugs safely.
- #48: `fix(cli): pass keyring secrets securely` — CLI keyring integrations do not expose encryption secrets through process arguments or command scripts.
- #50: `fix(cli): prevent init admin signature replay` — init-admin wallet signatures are bound to instance, username, nonce, and expiry.
- #51: `fix(privacy): strengthen partial hashes` — Partial privacy hashes derive from HMAC digest bytes rather than constant-prefixed strings.

## Specialist walks referenced
- Federation trust: as applicable per child issue
- Contract: backward-compatible semantic refinements via preserve-mastodon-api-compat
- Schema: none expected

## Parent acceptance
All child issues are closed, full local hard gate has passed for the milestone PR(s), and rollout notes are ready for dev → staging → live.

## Validation
- `go test ./...`
- `go vet ./...`
- `gofmt -l .`
- `go build -o lesser ./cmd/lesser`
- `./lesser build lambdas`
- `./lesser verify ci`

## Stage rollout checkpoints
- Merged to main
- Deployed to dev
- Dev soak complete
- Deployed to staging (if used)
- Staging soak complete
- Deployed to live
- Post-deploy monitoring verified

### LINKED ISSUE #869: fix(api): restore restrictive browser security headers
**Source**: Codex security findings roadmap, M9
**Enumerated item**: #45
**Parent issue**: https://github.com/equaltoai/lesser/issues/868

## Paths
cmd/api/main.go; cmd/api/middleware.go; docs/configuration.md

## Surface
cmd/lambda or REST handler, docs/contracts

## Classification
security hardening; labels: security, mastodon-compat

## Specialist walks referenced
- Federation trust: none
- Contract: backward-compatible semantic refinement via preserve-mastodon-api-compat
- Schema: none
- Framework: idiomatic lesser usage; no AppTheory/TableTheory patch planned

## Acceptance criterion
CORS/security headers are restrictive by default while preserving documented operator configuration points.

## Validation commands
- targeted package tests for touched code
- `go test ./...`
- `go vet ./...`
- `gofmt -l .`
- milestone hard gate before PR readiness: `go build -o lesser ./cmd/lesser && ./lesser build lambdas && ./lesser verify ci`

## Stage rollout checkpoints
- Merged to main
- Deployed to dev
- Dev soak complete
- Deployed to staging (if used)
- Staging soak complete
- Deployed to live
- Post-deploy monitoring verified

## Planned commit subject
`fix(api): restore restrictive browser security headers`

### LINKED ISSUE #870: fix(frontend): protect ssr link responses
**Source**: Codex security findings roadmap, M9
**Enumerated item**: #46
**Parent issue**: https://github.com/equaltoai/lesser/issues/868

## Paths
infra/cdk/constructs/frontend_response_headers.go; infra/cdk/stacks/lesser_api_stack.go; infra/cdk/assets/client_ssr_host/index.mjs

## Surface
repo code

## Classification
security hardening; labels: security, docs

## Specialist walks referenced
- Federation trust: none
- Contract: none expected
- Schema: none
- Framework: idiomatic lesser usage; no AppTheory/TableTheory patch planned

## Acceptance criterion
SSR /l placeholder responses escape Host-derived values and receive CSP/security headers.

## Validation commands
- targeted package tests for touched code
- `go test ./...`
- `go vet ./...`
- `gofmt -l .`
- milestone hard gate before PR readiness: `go build -o lesser ./cmd/lesser && ./lesser build lambdas && ./lesser verify ci`

## Stage rollout checkpoints
- Merged to main
- Deployed to dev
- Dev soak complete
- Deployed to staging (if used)
- Staging soak complete
- Deployed to live
- Post-deploy monitoring verified

## Planned commit subject
`fix(frontend): protect ssr link responses`

### LINKED ISSUE #871: fix(release): harden asset packaging
**Source**: Codex security findings roadmap, M9
**Enumerated item**: #47
**Parent issue**: https://github.com/equaltoai/lesser/issues/868

## Paths
pkg/releaseassets/files.go; pkg/releaseassets/auth_ui.go; cmd/lesser/up_release_assembly.go

## Surface
cmd/lambda or REST handler

## Classification
security hardening; labels: security, reliability, cli

## Specialist walks referenced
- Federation trust: none
- Contract: none expected
- Schema: none
- Framework: idiomatic lesser usage; no AppTheory/TableTheory patch planned

## Acceptance criterion
Release packaging refuses unsafe symlinks and release assembly handles hyphenated slugs safely.

## Validation commands
- targeted package tests for touched code
- `go test ./...`
- `go vet ./...`
- `gofmt -l .`
- milestone hard gate before PR readiness: `go build -o lesser ./cmd/lesser && ./lesser build lambdas && ./lesser verify ci`

## Stage rollout checkpoints
- Merged to main
- Deployed to dev
- Dev soak complete
- Deployed to staging (if used)
- Staging soak complete
- Deployed to live
- Post-deploy monitoring verified

## Planned commit subject
`fix(release): harden asset packaging`

### LINKED ISSUE #872: fix(cli): pass keyring secrets securely
**Source**: Codex security findings roadmap, M9
**Enumerated item**: #48
**Parent issue**: https://github.com/equaltoai/lesser/issues/868

## Paths
cmd/lesser/auth_keyring_darwin.go; cmd/lesser/auth_keyring_windows.go

## Surface
cmd/lambda or REST handler

## Classification
security hardening; labels: security, cli, auth

## Specialist walks referenced
- Federation trust: none
- Contract: none expected
- Schema: none
- Framework: idiomatic lesser usage; no AppTheory/TableTheory patch planned

## Acceptance criterion
CLI keyring integrations do not expose encryption secrets through process arguments or command scripts.

## Validation commands
- targeted package tests for touched code
- `go test ./...`
- `go vet ./...`
- `gofmt -l .`
- milestone hard gate before PR readiness: `go build -o lesser ./cmd/lesser && ./lesser build lambdas && ./lesser verify ci`

## Stage rollout checkpoints
- Merged to main
- Deployed to dev
- Dev soak complete
- Deployed to staging (if used)
- Staging soak complete
- Deployed to live
- Post-deploy monitoring verified

## Planned commit subject
`fix(cli): pass keyring secrets securely`

### LINKED ISSUE #873: fix(cli): prevent init admin signature replay
**Source**: Codex security findings roadmap, M9
**Enumerated item**: #50
**Parent issue**: https://github.com/equaltoai/lesser/issues/868

## Paths
cmd/lesser/init_admin.go

## Surface
cmd/lambda or REST handler

## Classification
security hardening; labels: security, cli, auth

## Specialist walks referenced
- Federation trust: none
- Contract: none expected
- Schema: none
- Framework: idiomatic lesser usage; no AppTheory/TableTheory patch planned

## Acceptance criterion
init-admin wallet signatures are bound to instance, username, nonce, and expiry.

## Validation commands
- targeted package tests for touched code
- `go test ./...`
- `go vet ./...`
- `gofmt -l .`
- milestone hard gate before PR readiness: `go build -o lesser ./cmd/lesser && ./lesser build lambdas && ./lesser verify ci`

## Stage rollout checkpoints
- Merged to main
- Deployed to dev
- Dev soak complete
- Deployed to staging (if used)
- Staging soak complete
- Deployed to live
- Post-deploy monitoring verified

## Planned commit subject
`fix(cli): prevent init admin signature replay`

### LINKED ISSUE #874: fix(privacy): strengthen partial hashes
**Source**: Codex security findings roadmap, M9
**Enumerated item**: #51
**Parent issue**: https://github.com/equaltoai/lesser/issues/868

## Paths
pkg/privacy/hasher.go

## Surface
repo code

## Classification
security hardening; labels: security, privacy

## Specialist walks referenced
- Federation trust: none
- Contract: none expected
- Schema: none
- Framework: idiomatic lesser usage; no AppTheory/TableTheory patch planned

## Acceptance criterion
Partial privacy hashes derive from HMAC digest bytes rather than constant-prefixed strings.

## Validation commands
- targeted package tests for touched code
- `go test ./...`
- `go vet ./...`
- `gofmt -l .`
- milestone hard gate before PR readiness: `go build -o lesser ./cmd/lesser && ./lesser build lambdas && ./lesser verify ci`

## Stage rollout checkpoints
- Merged to main
- Deployed to dev
- Dev soak complete
- Deployed to staging (if used)
- Staging soak complete
- Deployed to live
- Post-deploy monitoring verified

## Planned commit subject
`fix(privacy): strengthen partial hashes`

### PR DESCRIPTION
**Pull request by aron23**
## Milestone
[Codex Security M9] Browser, CLI, release, and secret hardening

## Classification
security hardening / contract-stability / operational reliability / privacy

## Surfaces affected
- API browser CORS, API Gateway preflight behavior, and default security headers
- Frontend `/l/*` SSR placeholder/error responses and CloudFront response headers policy
- Release asset packaging and release assembly template rewriting
- CLI keyring storage on macOS and Windows
- `init-admin` consent-message validation and signature replay controls
- Privacy partial-hash derivation

## Specialist walks referenced
- Federation trust: no ActivityPub signing, inbox/outbox, actor identity, delivery, or moderation trust-path changes.
- Contract / API: semantic browser-security refinement only. No Mastodon REST JSON shape, endpoint signature, pagination, or error-envelope changes. Browser CORS now defaults to the instance origin; operators with intentional cross-origin browser clients must configure `API_CORS_ALLOWED_ORIGINS` / `--api-cors-allowed-origins` / managed `api_cors_allowed_origins`.
- Schema: no DynamoDB PK/SK, GSI, TableTheory tag, or stream-event changes.
- Framework: uses AppTheory/CDK surfaces idiomatically; no AppTheory/TableTheory patches.

### Proposed change
Tighten browser-facing defaults by restoring restrictive browser security headers and fail-closed CORS origin defaults while preserving Mastodon-compatible API request and response bodies.

### Surfaces affected
- Mastodon REST: `/api/v1/*` browser fetch behavior via CORS/security headers only; response JSON unchanged.
- GraphQL: none.
- Streaming / subscriptions: no envelope change.
- ActivityPub actor / objects / collections: none.
- WebFinger / NodeInfo: none.

### Compatibility classification
Semantic refinement. Standards-shaped API clients are unaffected; browser clients running from origins other than the lesser instance origin now require explicit operator allowlisting.

### Consumer-class enumeration
- Mastodon clients: native/mobile clients unaffected; browser-hosted clients on non-instance origins need operator CORS configuration.
- Remote ActivityPub servers: unaffected.
- Sibling equaltoai repos: `host` coordination required for structured `init-admin` consent messages; `greater`/`sim` should verify browser-origin expectations during stage soak.
- Direct API integrators/operator tooling: release-note advisory required for `API_CORS_ALLOWED_ORIGINS`, `--api-cors-allowed-origins`, managed `api_cors_allowed_origins`, and `init-admin` consent message format.

### Versioning and rollout
- Transition mechanism: same endpoints and JSON contracts; operator configuration for non-default browser origins; managed provisioning must sign the structured consent JSON.
- Consumer validation stages: dev → staging (if used) → live.
- Rollback signal: browser CORS/preflight failures, SSR `/l/*` header regressions, init-admin provisioning errors, or release ingestion failures during dev/staging soak.
- OpenAPI / GraphQL regeneration: not required; `./lesser verify ci` confirmed contract files are current.

## Review follow-up
- Fixed the CORS split-brain finding: API Gateway REST `OPTIONS` responses no longer use wildcard AppTheory mock preflights. Deployed preflights now echo only the default instance origin or a normalized configured allowlist, and Lambda runtime CORS receives the same deploy-time allowlist.
- Fixed the macOS keyring regression: `security add-generic-password` keeps the secret off argv, restores the bare `-w` prompt path, and now feeds both matching password prompt entries through stdin.

## Consumer impact
- Operators with browser clients hosted on origins other than the lesser instance origin must set `API_CORS_ALLOWED_ORIGINS`, pass `lesser up --api-cors-allowed-origins`, or set managed provisioning `api_cors_allowed_origins` (legacy alias `CORS_ALLOWED_ORIGINS` remains accepted).
- Managed provisioning / `lesser-host` must send and sign structured `init-admin` consent JSON containing `kind`, `instance`, `username`, `nonce`, and `expires_at`; host has confirmed alignment and is sequencing its M4.5 before consuming this M9 release.
- Release packaging now rejects symlink/non-regular asset entries instead of following them.

## Tasks
- [x] Closes #869
- [x] Closes #870
- [x] Closes #871
- [x] Closes #872
- [x] Closes #873
- [x] Closes #874
- [x] Closes #868

## Validation
- `gofmt -l .` (empty)
- `GOOS=darwin GOARCH=arm64 go test -c -o /tmp/lesser-cmd-darwin.test ./cmd/lesser`
- `go test ./...`
- `go vet ./...`
- `(cd infra/cdk && go test ./...)`
- `go test ./pkg/security/cors ./cmd/api ./cmd/lesser ./pkg/releaseassets`
- `(cd infra/cdk && go test ./constructs ./stacks)`
- `go test ./pkg/privacy`
- `node --check infra/cdk/assets/client_ssr_host/index.mjs`
- `go run ./tools/audit_gates --check`
- `go build -o lesser ./cmd/lesser && ./lesser build lambdas && ./lesser verify ci`

Coverage from final `./lesser verify ci`:
- overall: 87.585%
- pkg: 90.027%
- cmd: 90.002%

## Stage rollout plan (handoff to deploy-instance)
- [ ] Merged to main
- [ ] Deployed to dev
- [ ] Dev soak complete
- [ ] Deployed to staging (if used)
- [ ] Staging soak complete
- [ ] Deployed to live

## Cross-repo coordination
- `lesser-host`: aligned with changes. Host is implementing Host Security M4.5 before consuming M9 so managed provisioning emits exact signed structured `init-admin` consent JSON and continues release checksum/lab-dry-run/canary verification.
- `greater` / `sim`: validate expected browser origins during dev/staging soak if they are hosted separately from the lesser instance origin.

## Advisor-brief authorization
Not advisor-dispatched.

### CODE REVIEW

File: cmd/lesser/auth_keyring_darwin.go [hunk 1]
```diff
@@ -48,12 +48,12 @@ func keyringSaveSecret(account string, secret string) error {
...
 	defer cancel()
 
-	cmd := exec.CommandContext(ctx, "security", "add-generic-password", //nolint:gosec // keychain tool invocation (secret is intended)
+	cmd := exec.CommandContext(ctx, "security", "add-generic-password", //nolint:gosec // keychain tool invocation
 		"-s", lesserCLIKeyringServiceName,
 		"-a", account,
-		"-w", secret,
 		"-U",
 	)
+	cmd.Stdin = strings.NewReader(secret + "\n")
```
Comment (aron23) [inline cmd/lesser/auth_keyring_darwin.go]: This moves the secret off argv, but the `security add-generic-password` invocation no longer includes the `-w` option. On macOS, `-w` is the option that supplies/prompts for the password data; setting `cmd.Stdin` alone does not attach stdin to the Keychain item’s password field. Net effect is that `lesser` credential save on macOS will fail or create an unusable item. Keep the non-argv path, but invoke the prompt form (for example `-w` at the end and feed the required stdin prompt input) or use a native API path.

**Review by aron23 — COMMENTED** [review]
Tier 1 grounded review at `ad47b85e`.

I would request changes if GitHub allowed that on this author/account. Two blockers:

1. **CORS is split between Lambda runtime and API Gateway preflight.** The PR tightens `cmd/api` AppTheory CORS defaults, but deployed REST preflights are still generated by `infra/cdk/constructs/api_routes.go` through `restAPICorsOptions()`, which only sets `AllowHeaders`. AppTheory CDK v1.2.0 defaults `allowOrigins ?? ["*"]` in `addCorsPreflightMethod`, so deployed `OPTIONS` still returns wildcard `Access-Control-Allow-Origin` and does not honor `API_CORS_ALLOWED_ORIGINS`. That leaves the PR contract (“browser CORS now defaults to the instance origin” / fail-closed origins) only true for Lambda-handled responses, not for the deployed preflight path. Cost to fix: either route API `OPTIONS` to the runtime CORS layer, or make deploy-time/API-Gateway CORS use the same origin policy and expose the allowlist through CDK/release deploy inputs. Cost of not fixing: disallowed origins can still pass preflight and dispatch side-effecting requests; operators also have no consistent IaC path for non-default browser origins.

2. **macOS keyring save appears to drop the password write path.** Inline note below: `security add-generic-password` no longer receives `-w`, so the stdin write is not connected to the Keychain password field. This breaks the macOS CLI credential save path while trying to remove the secret from argv.

Validation run locally in `agents/arch/branch-analysis/lesser-pr-901-review`:
- `git diff --check <base>..HEAD`
- gofmt over changed Go files (empty)
- `go test ./cmd/api ./cmd/lesser ./pkg/releaseassets ./pkg/privacy`
- `(cd infra/cdk && go test ./stacks ./constructs)`
- `node --check infra/cdk/assets/client_ssr_host/index.mjs`
- `go test ./...`
- `go vet ./...`
- `go build -o lesser ./cmd/lesser`
- `go run ./tools/audit_gates --check`
- `./lesser build lambdas`
- `./lesser verify ci` (overall 87.583%, pkg 90.023%, cmd 90.004%)

Sequencing note, not a separate blocker because the PR calls it out: current `lesser-host` still emits the older human-readable managed-provisioning consent message, while this PR requires the structured JSON message. Do not let managed provisioning consume this Lesser release until the lesser-host side is deployed.

File: cmd/lesser/auth_keyring_darwin.go (hunk 1 above)
Comment (aron23) [reply cmd/lesser/auth_keyring_darwin.go]: Follow-up at `9a089c5a`: this is closer, but I still would not clear the macOS keyring blocker yet.

The current command now invokes the prompt form:

```go
"-U",
"-w",
)
cmd.Stdin = strings.NewReader(secret + "\n")
```

But `security add-generic-password -w` without an argument enters the prompt path. The macOS `security` implementation prompts twice (`password data for new item:` and `retype password for new item:`) and only succeeds when the two reads match. A public Apple SecurityTool source mirror shows `promptForPasswordData` calling `getpass` for both prompts, and examples of the command show the same two-prompt behavior.

So with only `secret + "\n"`, the second prompt has no matching input; depending on whether `getpass` reads from the controlling TTY or stdin in the caller's environment, this will either hang until the 5s context timeout or fail the add. The secret is off argv now, but the write path still needs either:

- feed both prompt entries (`secret + "\n" + secret + "\n"`) and validate on macOS, or
- move this path to a native Keychain/SecItem API so the password data is provided directly without argv/prompt emulation.

References I used for the macOS behavior:
- public SecurityTool mirror: `promptForPasswordData` prompts twice and `-w` with no data enters that path: https://git.saurik.com/apple/security.git/blame/HEAD%3A/SecurityTool/macOS/keychain_add.c
- observed CLI behavior showing the two prompts: https://jpmens.net/2021/04/18/storing-passwords-in-macos-keychain/

**Review by aron23 — COMMENTED** [review]
Tier 1 grounded follow-up review at `9a089c5a`.

CORS split-brain blocker: **cleared**. The deploy path no longer relies on AppTheory's wildcard REST mock preflight defaults. The PR now:
- removes router-level REST `Cors` defaults in `infra/cdk/constructs/api_routes.go`,
- adds explicit mock `OPTIONS` integrations whose `Access-Control-Allow-Origin` is derived from a normalized default instance origin or normalized configured allowlist,
- plumbs `apiCorsAllowedOrigins` through CLI/env, managed provisioning input, release assembly parameters, CDK stack config, and Lambda env,
- shares origin normalization through `pkg/security/cors`.

macOS keyring blocker: **still open**. I replied on the existing thread. Restoring bare `-w` is the right direction, but the macOS prompt path asks for the new password twice; the current code feeds only `secret + "\n"`. That means the second prompt has no matching input, or the prompt may bypass `cmd.Stdin` via the controlling TTY. This path still needs a macOS-validated two-prompt feed or a native Keychain/SecItem implementation.

Validation I reran locally in `agents/arch/branch-analysis/lesser-pr-901-review`:
- `git diff --check <base>..HEAD`
- gofmt over changed Go files: empty
- `go test ./pkg/security/cors ./cmd/api ./cmd/lesser ./pkg/releaseassets ./pkg/privacy`
- `(cd infra/cdk && go test ./constructs ./stacks)`
- `node --check infra/cdk/assets/client_ssr_host/index.mjs`
- `go test ./...`
- `go vet ./...`
- `go build -o lesser ./cmd/lesser`
- `go run ./tools/audit_gates --check`
- `./lesser build lambdas`
- `./lesser verify ci` — overall 87.585%, pkg 90.025%, cmd 90.004%

GitHub status check observed through the connector: `security/snyk (equaltoai)` is still pending.

File: cmd/lesser/auth_keyring_darwin.go [hunk 2]
```diff
@@ -48,12 +48,13 @@ func keyringSaveSecret(account string, secret string) error {
...
 
-	cmd := exec.CommandContext(ctx, "security", "add-generic-password", //nolint:gosec // keychain tool invocation (secret is intended)
+	cmd := exec.CommandContext(ctx, "security", "add-generic-password", //nolint:gosec // keychain tool invocation
 		"-s", lesserCLIKeyringServiceName,
 		"-a", account,
-		"-w", secret,
 		"-U",
+		"-w",
 	)
+	cmd.Stdin = strings.NewReader(macOSKeychainPromptInput(secret))
```
Comment (aron23) [inline cmd/lesser/auth_keyring_darwin.go:58]: This now feeds both expected prompt entries, which fixes the earlier single-line prompt issue, but I still don't think this is reliable for the normal interactive macOS CLI path.

The `security add-generic-password -w` prompt path goes through `getpass()` in Apple's SecurityTool implementation. Apple's `getpass(3)` manual says it reads from `/dev/tty` first and only falls back to standard input if `/dev/tty` is inaccessible. `exec.Command` with `cmd.Stdin` set does not detach the child from the caller's controlling terminal, so an interactive `lesser` invocation can still have `/dev/tty` available and the `security` child will read the two prompts from the terminal rather than from this pipe. Net effect: the token is off argv, but the save path can still hang/prompt the user or time out instead of writing the supplied secret.

I would clear this if there is macOS manual evidence that this exact `exec.Command` shape consumes `cmd.Stdin` despite a controlling TTY. Otherwise the robust fixes are either to run the `security` prompt child without a controlling TTY and validate that fallback-to-stdin path on macOS, or to use a native Keychain/SecItem API path.

References:
- Apple `getpass(3)`: https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/getpass.3.html
- SecurityTool source mirror for the `-w` prompt path: https://git.saurik.com/apple/security.git/blame/HEAD%3A/SecurityTool/macOS/keychain_add.c

**Review by aron23 — COMMENTED** [review]
Tier 1 grounded follow-up review at `49d50085`.

Status:
- CORS split-brain blocker remains **cleared**.
- Snyk status is now **green** via the GitHub connector.
- Local validation passes.
- macOS keyring blocker is **still open**, but narrower than before.

What changed: `cmd/lesser/auth_keyring_darwin.go` now feeds `secret + "\n" + secret + "\n"` through `macOSKeychainPromptInput`, and static coverage asserts the bare `-w` form and double-prompt helper. That addresses my prior observation that the prompt path asks twice.

Remaining concern: Apple's `getpass(3)` reads from `/dev/tty` before falling back to stdin, and Apple's SecurityTool `-w` prompt path uses `getpass()`. Since this `exec.Command` does not detach the `security` child from the caller's controlling terminal, `cmd.Stdin` is not sufficient evidence that an interactive macOS CLI invocation will consume the pipe. It may still prompt/hang/time out instead of writing the supplied secret. I left the detailed inline note on the current line.

Cost accounting:
- Cost of not fixing: macOS users can still lose the CLI credential-save path even though tests and cross-compilation pass; the failure mode is likely a prompt/hang/timeout during auth save.
- Lower-cost fix: detach the `security` child from the controlling terminal so `getpass()` must fall back to stdin, then validate on macOS.
- Higher-cost but cleaner fix: native Keychain/SecItem API path to avoid prompt emulation entirely.

Validation run locally in `agents/arch/branch-analysis/lesser-pr-901-review`:
- `git diff --check <base>..HEAD`
- gofmt over changed Go files: empty
- `GOOS=darwin GOARCH=arm64 go test -c -o /tmp/lesser-cmd-darwin.test ./cmd/lesser`
- `go test ./cmd/lesser ./cmd/api ./pkg/security/cors ./pkg/releaseassets ./pkg/privacy`
- `(cd infra/cdk && go test ./constructs ./stacks)`
- `node --check infra/cdk/assets/client_ssr_host/index.mjs`
- `go test ./...`
- `go vet ./...`
- `go build -o lesser ./cmd/lesser`
- `go run ./tools/audit_gates --check`
- `./lesser build lambdas`
- `./lesser verify ci` — overall 87.585%, pkg 90.025%, cmd 90.004%

File: cmd/lesser/auth_keyring_darwin.go (hunk 2 above)
Comment (aron23) [reply cmd/lesser/auth_keyring_darwin.go:58]: Follow-up at `3460a1dd`: this clears my remaining macOS keyring blocker.

The new `cmd.SysProcAttr = &syscall.SysProcAttr{Setsid: true}` changes the part I was concerned about: the `security` child is placed in a new session without the caller's controlling terminal, so the `getpass(3)` path should be unable to use `/dev/tty` and should fall back to the supplied stdin pipe. Combined with the existing `secret + "\n" + secret + "\n"` helper, this matches the two-prompt `-w` path while keeping the secret off argv.

I could not live-execute macOS Keychain from this Linux review environment, but the code now matches the documented process-control behavior that was missing before. Cross-compilation for darwin `cmd/lesser` passed locally.

**Review by aron23 — COMMENTED** [review]
Tier 1 grounded follow-up review at `3460a1dd`.

The remaining macOS keyring blocker is **cleared** from my side. The PR now keeps the secret off argv, feeds both expected `security add-generic-password -w` prompt entries, and detaches the `security` child with `syscall.SysProcAttr{Setsid: true}` so `getpass(3)` should not be able to read from the caller's controlling terminal before falling back to stdin.

CORS split-brain remains cleared, and Snyk is green.

Validation run locally in `agents/arch/branch-analysis/lesser-pr-901-review`:
- `git diff --check <base>..HEAD`
- gofmt over changed Go files: empty
- `GOOS=darwin GOARCH=arm64 go test -c -o /tmp/lesser-cmd-darwin.test ./cmd/lesser`
- `go test ./cmd/lesser ./cmd/api ./pkg/security/cors ./pkg/releaseassets ./pkg/privacy`
- `(cd infra/cdk && go test ./constructs ./stacks)`
- `node --check infra/cdk/assets/client_ssr_host/index.mjs`
- `go test ./...`
- `go vet ./...`
- `go build -o lesser ./cmd/lesser`
- `go run ./tools/audit_gates --check`
- `./lesser build lambdas` — built 10, skipped 28 after the interrupted prior build had already produced the rest
- `./lesser verify ci` — overall 87.585%, pkg 90.025%, cmd 90.004%

No remaining Arch blocker from this pass. Rollout note still stands: managed provisioning should not consume this Lesser release until the lesser-host structured `init-admin` consent side is deployed.
